"""initial_schema

Revision ID: dc2cbddabb63
Revises: 
Create Date: 2026-03-21 22:23:37.856147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'dc2cbddabb63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('text_hash')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), server_default=sa.text("'starter'"), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), server_default=sa.text("'trialing'"), nullable=False),
    sa.Column('max_documents', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('max_queries_per_month', sa.Integer(), server_default=sa.text('10000'), nullable=False),
    sa.Column('max_storage_bytes', sa.BigInteger(), server_default=sa.text('10737418240'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index('idx_tenants_clerk_org', 'tenants', ['clerk_org_id'], unique=False)
    op.create_index('idx_tenants_stripe', 'tenants', ['stripe_customer_id'], unique=False, postgresql_where=sa.text('stripe_customer_id IS NOT NULL'))
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["read", "write"]\'::jsonb'), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_api_keys_tenant', 'api_keys', ['tenant_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('sync_frequency', sa.String(length=20), server_default=sa.text("'daily'"), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('exclude_patterns', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connectors_next_sync', 'connectors', ['next_sync_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_connectors_tenant', 'connectors', ['tenant_id'], unique=False)
    op.create_index('idx_connectors_type', 'connectors', ['tenant_id', 'connector_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'member'"), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'clerk_user_id', name='uq_users_tenant_clerk'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index('idx_users_clerk', 'users', ['clerk_user_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['tenant_id', 'email'], unique=False)
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_logs', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_tenant', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('idx_audit_tenant_date', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_audit_tenant_user', 'audit_logs', ['tenant_id', 'user_id'], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_tenant', 'conversations', ['tenant_id'], unique=False)
    op.create_index('idx_conversations_updated', 'conversations', ['tenant_id', 'updated_at'], unique=False)
    op.create_index('idx_conversations_user', 'conversations', ['tenant_id', 'user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('parent_document_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_filename', 'documents', ['tenant_id', 'filename'], unique=False)
    op.create_index('idx_documents_tenant', 'documents', ['tenant_id'], unique=False)
    op.create_index('idx_documents_tenant_created', 'documents', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_documents_tenant_status', 'documents', ['tenant_id', 'status'], unique=False)
    op.create_table('sync_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('files_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_skipped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_processed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_history_connector', 'sync_history', ['connector_id'], unique=False)
    op.create_index('idx_sync_history_started', 'sync_history', ['connector_id', 'started_at'], unique=False)
    op.create_index('idx_sync_history_tenant', 'sync_history', ['tenant_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('stripe_meter_event_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_tenant', 'usage_records', ['tenant_id'], unique=False)
    op.create_index('idx_usage_tenant_date', 'usage_records', ['tenant_id', 'recorded_at'], unique=False)
    op.create_index('idx_usage_tenant_type', 'usage_records', ['tenant_id', 'usage_type'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_document_index')
    )
    op.create_index('idx_chunks_content_hash', 'chunks', ['tenant_id', 'content_hash'], unique=False)
    op.create_index('idx_chunks_document', 'chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_tenant', 'chunks', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_feedback', 'messages', ['tenant_id', 'feedback'], unique=False, postgresql_where=sa.text('feedback IS NOT NULL'))
    op.create_index('idx_messages_tenant', 'messages', ['tenant_id'], unique=False)
    op.create_table('synced_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('external_path', sa.Text(), nullable=True),
    sa.Column('external_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_hash', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_synced_files_connector_ext')
    )
    op.create_index('idx_synced_files_connector', 'synced_files', ['connector_id'], unique=False)
    op.create_index('idx_synced_files_document', 'synced_files', ['document_id'], unique=False)
    op.create_index('idx_synced_files_tenant', 'synced_files', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synced_files_tenant', table_name='synced_files')
    op.drop_index('idx_synced_files_document', table_name='synced_files')
    op.drop_index('idx_synced_files_connector', table_name='synced_files')
    op.drop_table('synced_files')
    op.drop_index('idx_messages_tenant', table_name='messages')
    op.drop_index('idx_messages_feedback', table_name='messages', postgresql_where=sa.text('feedback IS NOT NULL'))
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_chunks_tenant', table_name='chunks')
    op.drop_index('idx_chunks_document', table_name='chunks')
    op.drop_index('idx_chunks_content_hash', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_usage_tenant_type', table_name='usage_records')
    op.drop_index('idx_usage_tenant_date', table_name='usage_records')
    op.drop_index('idx_usage_tenant', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('idx_sync_history_tenant', table_name='sync_history')
    op.drop_index('idx_sync_history_started', table_name='sync_history')
    op.drop_index('idx_sync_history_connector', table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_index('idx_documents_tenant_status', table_name='documents')
    op.drop_index('idx_documents_tenant_created', table_name='documents')
    op.drop_index('idx_documents_tenant', table_name='documents')
    op.drop_index('idx_documents_filename', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_conversations_user', table_name='conversations')
    op.drop_index('idx_conversations_updated', table_name='conversations')
    op.drop_index('idx_conversations_tenant', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_audit_tenant_user', table_name='audit_logs', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_audit_tenant_date', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_action', table_name='audit_logs')
    op.drop_index('idx_audit_tenant', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_clerk', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_connectors_type', table_name='connectors')
    op.drop_index('idx_connectors_tenant', table_name='connectors')
    op.drop_index('idx_connectors_next_sync', table_name='connectors', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('connectors')
    op.drop_index('idx_api_keys_tenant', table_name='api_keys')
    op.drop_index('idx_api_keys_prefix', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_tenants_stripe', table_name='tenants', postgresql_where=sa.text('stripe_customer_id IS NOT NULL'))
    op.drop_index('idx_tenants_clerk_org', table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
